Models/ErrorViewModel.cs
namespace RestApiForGeoData.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/LogWriter.cs
namespace RestApiForGeoData.Models
{
    using System.IO;
    using System.Reflection;


    public class LogWriter
    {
        private string m_exePath = string.Empty;
        public LogWriter(string logMessage)
        {
            LogWrite(logMessage);
        }
        public void LogWrite(string logMessage)
        {
            m_exePath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            try
            {
                using (StreamWriter w = File.AppendText(m_exePath + "\\" + "log.txt"))
                {
                    Log(logMessage, w);
                }
            }
            catch (Exception ex)
            {
            }
        }

        public void Log(string logMessage, TextWriter txtWriter)
        {
            try
            {
                txtWriter.Write("Лог : ");
                txtWriter.WriteLine("{0} {1}", DateTime.Now.ToLongTimeString(), DateTime.Now.ToLongDateString());
                txtWriter.WriteLine("  :{0}", logMessage);
                txtWriter.WriteLine("-------------------------------\r\n");
            }
            catch (Exception ex)
            {
            }
        }
    }
}

Controllers/DataController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestSharp;
using System.Linq;
using RestApiForGeoData.Models;

namespace RestApiForGeoData.Controllers
{
    public class DataController : Controller
    {
        [HttpPost]
        public IActionResult Index(string country, string city, string street)
        {

            LogWriter logWriter;

            string log;

            dynamic dataDadata;

            dynamic dataOpenstreetmap = Openstreetmap(country, city, street);


            if (dataOpenstreetmap.Count > 0)
            {
                try
                {
                    dataDadata = Dadata(dataOpenstreetmap[0].lat, dataOpenstreetmap[0].lon);

                    ViewBag.lon = dataOpenstreetmap[0].lon;

                    ViewBag.lat = dataOpenstreetmap[0].lat;

                    logWriter = new LogWriter($"Успешный поиск по адресу: '{country}' '{city}' '{street}'");

                    return View(dataDadata);
                }
                catch (Exception ex)
                {
                    logWriter = new LogWriter($"Ошибка '{ex.Message}' при поиске по адресу: '{country}' '{city}' '{street}'");

                    return BadRequest(ex);
                }
            }
            else
            {
                string message = "Нет результатов";
                logWriter = new LogWriter($"Ошибка '{message}' при поиске по адресу: '{country}' '{city}' '{street}'");
                return BadRequest(message);
            }
            
        }


        public dynamic Dadata<T>(T lat, T lon)
        {
            string url = $"https://suggestions.dadata.ru/suggestions/api/4_1/rs/geolocate/address";
            
            RestRequest request = new RestRequest(url, Method.Post);
            request.AddHeader("Content-Type", "application/json");
            request.AddHeader("Accept", "application/json");
            request.AddHeader("Authorization", "Token 48ecca72935291047a107f7becf0e2036ba98742");

            request.AddBody(JsonConvert.SerializeObject(new { lat = lat, lon = lon, count = 10 }));
            
            dynamic data = RestClient(url, request);

            return data;
        }


        public dynamic Openstreetmap(string country, string city, string street)
        {
            string url = $"https://nominatim.openstreetmap.org/search?country={country}&city={city}&street={street}&format=json&limit=2";
            
            RestRequest request = new RestRequest(url, Method.Get);

            dynamic data = RestClient(url, request);

            return data;


        }


        public dynamic RestClient(string url, RestRequest request)
        {
            RestClient client = new RestClient(url);

            var response = client.Execute(request);

            string stream = response.Content;

            var data = JsonConvert.DeserializeObject(stream);

            return data;
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestApiForGeoData.Models;
using RestSharp;
using System.Diagnostics;

namespace RestApiForGeoData.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

    }
}

Views/Data/Index.cshtml
@model dynamic



<p>Широта: @ViewBag.lat</p>
<p>Долгота: @ViewBag.lon</p>

@{
	int i = 1;
	foreach(var item in @Model.suggestions)
	{
		if (i <= 10)
		{
			<p>@i) @item.unrestricted_value</p>

			i++;
		}
	}
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<form asp-controller="Data" asp-action="Index" method="post">
    <input placeholder="Введите страну" name="country"/><br />
    <input placeholder="Введите город" name="city"/><br />
    <input placeholder="Введите улицу" name="street"/><br />
    <input type="submit"/>

</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestApiForGeoData</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RestApiForGeoData.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RestApiForGeoData</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RestApiForGeoData - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>